### ISSUE TITLE
Resets UTime

### ISSUE THREAD

**Issue by MilkGames** [MilkGames/betterspawnprotection#2]
> Good Job, resets UTime on my server. and as soon as i remove the addon it gets fixed - https://steamcommunity.com/workshop/filedetails/discussion/1573138758/1742226629867054162/#c1742226629873899923

アニメ Cyber

**Comment by MilkGames** [comment]
This shouldn't reset UTime, can you give more information?

Also - Did this happen after the latest update? The latest update doesn't seem to work on dedicated servers, I'll have to take a look to make sure it's not an isolated case. For now I'll roll back the update.

**Comment by TheCyberDiamond** [comment]
I dont think its a coincidence that it resets everything as soon as a changemap/ restart occurs,

**Comment by MilkGames** [comment]
Closed, no repro steps.
